city_names = ["Alicante",
              "Brest",
              "Dakar",
              "Glasgow",
              "Hamburg",
              "London",
              "Montpellier",
              "Nairobi",
              "Oran",
              "Paris",
              "Quito",
              "Rennes",
              "Strasbourg",
              "Tokyo",
              ]