city_names = ["Alicante",
              "Beyrouth",
              "Buenos Aires",
              "Conakry",
              "Dakar",
              "Esperance",
              "Fethiye", 
              "Glasgow",
              "Hamburg",
              "Istanbul",
              "Jaipur",
              "Kuala Lumpur",
              "London",
              "Montpellier",
              "Mumbai",
              "Nairobi",
              "Narvik",
              "Oran",
              "Paris",
              "Phoenix",
              "Quito",
              "Rennes",
              "Reykjavik",
              "Riyadh",
              "Shanghai",
              "Strasbourg",
              "Tokyo",
              "Ulaanbaatar",
              "Valparaiso",
              "Verkhoyansk",
              "Wellington",
              "Windhoek",
              "Xiongzhou",
              "Yakutsk",
              "Yaounde",
              "Zarqa"
              ]
